### ISSUE TITLE
The attribute "Include" in element <Compile> is unrecognized.

### ISSUE THREAD

**Issue by responsiblet** [einsteinx2/WaveBox#216]
The error in VS2012 is
C:...\GitHub\WaveBox\WaveBox.Server\WaveBox.Server.csproj : error  : The attribute "Include" in element <Compile> is unrecognized.  C:...\GitHub\WaveBox\WaveBox.Server\WaveBox.Server.csproj

I cannot compile.  Any help would be greatly appreciated.  Until then, I am downloading VS2013 in hopes that something may have changed.

**Comment by einsteinx2** [comment]
Looks like this is fixed.
