### ISSUE TITLE
Custom CSS/JS doesn't work in frames/iframes

### ISSUE THREAD

**Issue by Naatan** [einsteinx2/WaveBox#218]
I tried styling the chat frame in hangouts, which is an iframe. Unfortunately it seems the custom CSS only gets loaded on the top level window. Would be nice if this worked on all windows that are loaded in the relevant browser session.

**Comment by einsteinx2** [comment]
Hi @Naatan, thanks for the bug report. Currently the project is on hiatus, though I'm planning to continue work on the server component and officially release it later this year to provide a free and easy to setup backend for iSub, my iOS app. Unfortunately I have pretty much zero web dev experience, so the web interface will continue to be "beta" until I find someone that can contribute in that area.

**Comment by Naatan** [comment]
I apologize, it seems I reported to the wrong wavebox repository.
